import './blocks/variables';
import './blocks/brends';
import './blocks/call';
import './blocks/equipments';
import './blocks/feedback';
import './blocks/info';
import './blocks/menu';
import './blocks/swiper';
import '../scss/styles.scss';